version: "3.8"

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: amel_tech
      POSTGRES_PASSWORD: ameltech
      POSTGRES_DB: mr_taha_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: crud_api
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://amel_tech:ameltech@database:5432/mr_taha_db

volumes:
  postgres_data:
